# Nginx ile statik dosyaları sunmak için bir Dockerfile
FROM nginx:alpine

# Custom Nginx config file
COPY nginx.conf /etc/nginx/nginx.conf

# Statik dosyaları frontend klasöründen kopyala
COPY ./frontend /usr/share/nginx/html

# Nginx'in 80 portunu aç
EXPOSE 80

# Nginx'i başlat
CMD ["nginx", "-g", "daemon off;"]
